Scoreboard:
  Title: "%prefix% &6&lLightningCore"
Messages:
  Points-Set: "&7You just set &e%player%'s points to &e%amount%&7."
  Points-Add: "&7You have added &e%amount% &7to  &e%player%'s &7balance."
  Points-Remove: "&7You have removed &e%amount% &7from &e%player%'s &7balance."
  Points-View: "&e%player%'s &7Points Balance: &e%amount%"
  Points-Received: "&7You just received &e%amount% &7points."
Crew-Admin-Usage:
  - "&b---------------------------------------------------"
  - ""
  - "&b/CrewAdmin check <player> &7- Check players point balance"
  - " "
  - "&b/CrewAdmin add <player> <amount> &7- &fAdd points to a players balance"
  - " "
  - "&b/CrewAdmin remove <player> <amount> &7- &fRemove points from a players balance"
  - " "
  - "&b/CrewAdmin set &7- &fSet a players point balance"
  - " "
  - "&b---------------------------------------------------"
TopKills:
  inventory:
    title: "&e&lTop Kills Leaderboard"
    size: 36
    items:
      0:
        item: "PLAYER_HEAD"
        name: "&e&l%position%"
        lore:
          - ""
          - "&6%player%&7 &f(%kills%)"
        slot: 11
broadcasts-enabled: true
broadcast-interval: 3600
Broadcasts:
  0:
    sound: "BLOCK_NOTE_BLOCK_CHIME"
    messages:
      - '%prefix% &7Visit our website - play.test.rip'
  1:
    sound: "BLOCK_NOTE_BLOCK_HARP"
    messages:
      - ' '
      - '%prefix% &6Visit our discord @ test.discordserver.rip'
      - ' '
