Crews-Settings:
  usage:
    - "&b--------------------"
    - ""
    - "&b/Crew create <name> &7- &fCreate a crew"
    - " "
    - "&b/Crew disband &7- &fDisband the crew (must be leader)"
    - " "
    - "&b/Crew leave &7- &fLeave your current crew"
    - " "
    - "&b/Crew points &7- &fCheck your crews points"
    - " "
    - "&b/Crew pointtop &7- &fCheck the crew top leaderboard"
settings: # if false message will be sent to player which executed this command
  created-broadcast: true
  disbanded-broadcast: true
messages:
  permission-leader: "&cYou need to have leader role to execute this command"
  permission-captain: "&cYou need at least captain role to execute this command"
  permission-coleader: "&cYou need at least coleader role to execute this command"
  exists: "&cCrew %crew% already exists"
  not-exists: "&cCrew %crew% does not exists."
  created: "&cCrew %crew% has been created"
  disbanded: "&cCrew %crew% has been disbanded"
  no-Crew: "&cYou need to be in Crew to execute this command"
  renamed: "&cCrew %crew% has renamed to %renamed%"
  in-Crew: "&cYou are already in Crew"
  leave-leader: "&cYou cannot leave your own faction (/Crew disband)"
  left: "&cYou have left %crew%"
  home-set: "&cCrew home has been set"
  home: "&cTeleported"
  home-teleport: "&cYou will be teleport to home in 10 seconds"
  no-home: "&cNo home has been set."
  teleport-moved: "&cTeleportation has been cancelled player moved."
  no-invite: "&c%crew% has not invited you."
  invites: "&cYou have been invited to %crews%"
  deposit: "&cYou have deposit %points% to faction"
  withdraw: "&cYou have withdrawn %points% from crew"
  invitation: "&cYou have been invited to %crew%"
  your-crew: "&cPlayer is already in your crew."
  withdraw-failed: "&cFailed to withdraw %amount% from crew."
  deposit-failed: "&cFailed to deposit %amount% to the crew."
  list: "&ecrew&7: &f%crew% &eBalance&7: &f%balance%" # it will be in column
  list-failed: "&cNone"
  top: "&7%crew_number%. &c%crew_name% &e- &7%crew_points%"
  top-failed: "&cNone"