name: LightningCore
api-version: 1.16
Author: Jack/Snowey
version: 0.1
main: net.jack.lightning.LightningCore
commands:
  crew:
    description: Crews
  spleef:
    description: Spleef
  points:
    description: Points
  crewadmin:
    description: Admin commands for crew
  killstop:
    description: Top kills
  lc:
    description: Lightning Core
  harvesterhoe:
    description: Harvester Hoe
    aliases:
      - hh